name: PickaxeLock
version: '${project.version}'
main: me.mynqme.pickaxelock.PickaxeLock
api-version: 1.12
authors: [MyNqme]
description: 1.12 Version of PickaxeLock
commands:
  pickaxelock:
    description: Opens the gui to change your pickaxe slot!
    usage: /<command>
    aliases: [prisonspicklock, prisonpicklock, picklock, prisonspickaxelock, prisonpickaxelock, changeslot, lock]